version: '3.8'

services:
  geth:
    image: ethereum/client-go:latest
    container_name: jsonrpc-bench-geth
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./data:/root/.ethereum
    command:
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,debug
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3,debug
      - --ws.origins=*
      - --syncmode=snap
      - --cache=4096
      - --rpc.allow-unprotected-txs
      # Use one of the following for network selection
      # - --sepolia  # For Sepolia testnet
      # - --holesky  # For Holesky testnet
      # - --dev      # For local development chain
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
