package promsink

import (
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const goldenPath = "testdata/k6-series.golden"

// k6Families is every metric family the k6 output produced, and therefore every
// family the replacement engine has to either emit an equivalent for or drop
// deliberately. The native engine's own capture is checked against this list so
// a signal cannot go missing unnoticed during the migration.
var k6Families = []string{
	"k6_checks_rate",
	"k6_data_received_total",
	"k6_data_sent_total",
	"k6_dropped_iterations_total",
	"k6_group_duration",
	"k6_http_req_blocked",
	"k6_http_req_connecting",
	"k6_http_req_duration",
	"k6_http_req_failed_rate",
	"k6_http_req_receiving",
	"k6_http_req_sending",
	"k6_http_req_tls_handshaking",
	"k6_http_req_waiting",
	"k6_http_reqs_total",
	"k6_iteration_duration",
	"k6_iterations_total",
	"k6_vus",
	"k6_vus_max",
}

// trendStats are the suffixes k6 appends for a trend metric, driven by
// K6_PROMETHEUS_RW_TREND_STATS. Note p999, not p99_9: the collector that read
// these back matched on "p99_9" and silently dropped p99.9 as a result.
var trendStats = []string{"avg", "max", "med", "min", "p75", "p90", "p95", "p99", "p999"}

func loadGolden(t *testing.T) (map[string]string, []string) {
	t.Helper()
	data, err := os.ReadFile(goldenPath)
	require.NoError(t, err)
	headers, keys, err := ParseGolden(data)
	require.NoError(t, err)
	return headers, keys
}

// The capture is regenerated by pointing a run at the sink:
//
//	go run ./runner/cmd/stubnode -config stub.json &
//	go run ./runner/cmd/promsink -source "k6 vX.Y.Z" -golden runner/internal/promsink/testdata/k6-series.golden &
//	go run ./runner benchmark --config bench.yaml --clients clients.yaml \
//	    --prometheus http://127.0.0.1:19090 --prometheus-rw-user u --prometheus-rw-pass p
//
// The committed file is the union of a healthy run and a VU-starved one, because
// several series only exist when something goes wrong: the error/error_code
// labels appear only on failing requests, and dropped_iterations only when the
// arrival rate outruns the VUs.
func TestGoldenIsWellFormed(t *testing.T) {
	headers, keys := loadGolden(t)

	assert.Equal(t, "snappy", headers["Content-Encoding"])
	assert.Equal(t, "application/x-protobuf", headers["Content-Type"])
	assert.Equal(t, "0.1.0", headers["X-Prometheus-Remote-Write-Version"])
	assert.Contains(t, headers["User-Agent"], "k6")
	assert.Equal(t, "basic <redacted>", headers["Authorization"],
		"remote-write auth must be exercised by the capture but never written to it")

	assert.NotEmpty(t, keys)
	assert.Equal(t, keys, sortedCopy(keys), "series must stay sorted so the file diffs cleanly")

	for _, key := range keys {
		assert.True(t, strings.HasSuffix(key, "}"), "malformed series key %q", key)
		assert.NotContains(t, key, "__name__", "the metric name belongs before the brace, not in the labels")
	}
}

func TestGoldenCoversEveryK6Family(t *testing.T) {
	_, keys := loadGolden(t)

	present := make(map[string]bool, len(keys))
	for _, key := range keys {
		name, _, _ := strings.Cut(key, "{")
		present[name] = true
		for _, stat := range trendStats {
			if base, ok := strings.CutSuffix(name, "_"+stat); ok {
				present[base] = true
			}
		}
	}

	for _, family := range k6Families {
		assert.True(t, present[family], "family %s is missing from %s", family, goldenPath)
	}
}

// Every latency family must carry all nine stats, since the dashboard's stat
// picker is populated by discovery over the emitted names.
func TestGoldenTrendFamiliesAreComplete(t *testing.T) {
	_, keys := loadGolden(t)

	names := make(map[string]bool, len(keys))
	for _, key := range keys {
		name, _, _ := strings.Cut(key, "{")
		names[name] = true
	}

	for _, family := range []string{
		"k6_http_req_duration",
		"k6_http_req_waiting",
		"k6_http_req_sending",
		"k6_http_req_receiving",
		"k6_http_req_blocked",
		"k6_http_req_connecting",
		"k6_http_req_tls_handshaking",
		"k6_iteration_duration",
	} {
		for _, stat := range trendStats {
			assert.True(t, names[family+"_"+stat], "%s_%s is missing from %s", family, stat, goldenPath)
		}
	}
}

// The label keys a dashboard query can group by. Recorded here because the
// migration drops four of them (url, group, error, error_code) and adds an
// outcome label, and that choice should fail a test if it is made by accident.
func TestGoldenRequestLabels(t *testing.T) {
	_, keys := loadGolden(t)

	seen := make(map[string]bool)
	for _, key := range keys {
		if !strings.HasPrefix(key, "k6_http_reqs_total{") {
			continue
		}
		_, labels, _ := strings.Cut(key, "{")
		for _, label := range strings.Split(strings.TrimSuffix(labels, "}"), ",") {
			seen[label] = true
		}
	}

	for _, label := range []string{"testid", "scenario", "client_type", "req_name", "rpc_method", "status", "url", "group", "error", "error_code"} {
		assert.True(t, seen[label], "label %s is missing from the k6_http_reqs_total capture", label)
	}
	assert.False(t, seen["expected_response"],
		"k6 never emitted expected_response because it is absent from the generated systemTags, which is why four dashboard panels return no data")
}

func sortedCopy(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}
