version: '3.8'

services:
  nethermind:
    image: nethermind/nethermind:latest
    container_name: jsonrpc-bench-nethermind
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./data:/data
    environment:
      - NETHERMIND_JSONRPCCONFIG_ENABLED=true
      - NETHERMIND_JSONRPCCONFIG_HOST=0.0.0.0
      - NETHERMIND_JSONRPCCONFIG_PORT=8545
      - NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES=["Eth","Net","Web3","Debug"]
      - NETHERMIND_WEBSOCKETSCONFIG_ENABLED=true
      - NETHERMIND_WEBSOCKETSCONFIG_HOST=0.0.0.0
      - NETHERMIND_WEBSOCKETSCONFIG_PORT=8546
      # Use one of the following for network selection
      # - NETHERMIND_CONFIG=sepolia  # For Sepolia testnet
      # - NETHERMIND_CONFIG=holesky  # For Holesky testnet
      # - NETHERMIND_CONFIG=mainnet  # For Mainnet
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
